### ISSUE TITLE
notifyURL and returnURL override does not work

### ISSUE THREAD

**Issue by patrickmcl** [stephenlake/AddPay-PHP-SDK#4]
The API is not overwriting what is configred in Admin

**Comment by stephenlake** [comment]
Unable to replicate this issue. Please provide logs and the full payload of attempts made.

**Comment by stephenlake** [comment]
Closing since it has been made clear that invalid functions are being called:
![Screenshot](https://i.imgur.com/5DFaF8U.png)

The above payload is incorrect and will not produce the required result as the documentation specifically describes here, **_please read the documentation_**:
![Screenshot](https://i.imgur.com/0dM8LIm.png)
