### ISSUE TITLE
Initiate date is not working

### ISSUE THREAD

**Issue by patrickmcl** [stephenlake/AddPay-PHP-SDK#5]
The Initiate date is not working, It takes the datetime of the transaction, and not the requested date.  It was set it to 2017-03-1, but the following dates were returned, and it missed February, and then randomly selected 2nd of the month,
 
[initiates_at] => 2018-01-30 20:37:50
[initiates_at] => 2018-03-02 20:37:50
[initiates_at] => 2018-04-02 20:37:50
[initiates_at] => 2018-05-02 20:37:50
[initiates_at] => 2018-06-02 20:37:50
[initiates_at] => 2018-07-02 20:37:50
[initiates_at] => 2018-08-02 20:37:50
[initiates_at] => 2018-09-02 20:37:50
[initiates_at] => 2018-10-02 20:37:50
[initiates_at] => 2018-11-02 20:37:50
[initiates_at] => 2018-12-02 20:37:50
[initiates_at] => 2019-01-02 20:37:50
 
If a date is not valid in a month (eg: 30th Feb) then it shouldn't it default to the last day of that month.

**Comment by stephenlake** [comment]
Can't replicate. Please provide a sample of the JSON payload and note the field name is *initiates_at* not initiate_at.

**Comment by stephenlake** [comment]
Closing since it has been made clear that invalid functions are being called:
![Screenshot](https://i.imgur.com/5DFaF8U.png)

The above payload is incorrect and will not produce the required result as the documentation specifically describes here, **_please read the documentation_**:
![Screenshot](https://i.imgur.com/0dM8LIm.png)
